#!/usr/bin/env -S display_file_shell -l bash
Stannous chloride: 0.5g
Thiourea: 2.0g
Sulfamic acid: 3.0g
Distilled water: 100ml

You can premix ingredients in bulk, and measure out 5.5g of powder / 100ml.

Heat water, mix in ingredients until dissolved.
Dip.
