#!/bin/bash

cat <<'EOT'
In linux:
  modprobe ftdi_sio
  (and maybe: modprobe usbserial)

(My wire coloring. Choose your own.)
Probe Color  Wire Color  Sonoff S31  FTDI USB Adapter
Yellow       Blue        TX          RX
Green        Brown       RX          TX
Blue         Red         VCC         VCC
Yellow       Yellow      GND         GND

               Hook/Wire Color
               Y/Y        Y/B G/Br  Bl/R
.---------------------------------------.
|               o   o   o   o   o   o   |
|               G           Tx  Rx  Vcc |
|                                       |
|           Sonoff Daughterboard        |
|                                       |


USB Serial Adapter:
|                    |
|                    |
|__.__.__.__.__.__.__|
   |  |  |  |  |  |
 dtr rx tx v+ cts g
 
     
EOT
